package scripts;

import javax.swing.JFrame;

@SuppressWarnings("serial")
public class OriginalGUI extends javax.swing.JFrame {

    /**
     * Creates new form PCGUI
     */
    public OriginalGUI() {
        //initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    public void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        meleeCombatButton = new javax.swing.JRadioButton();
        mageCombatButton = new javax.swing.JRadioButton();
        rangeCombatButton = new javax.swing.JRadioButton();
        specialAttackYesButton = new javax.swing.JRadioButton();
        specialAttackNoButton = new javax.swing.JRadioButton();
        specialAttackLabel = new javax.swing.JLabel();
        attackPortalButton = new javax.swing.JRadioButton();
        defendButton = new javax.swing.JRadioButton();
        randomButton = new javax.swing.JRadioButton();
        methodOfCombatLabel = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        clanChatLabel = new javax.swing.JLabel();
        ccTextField = new javax.swing.JTextField();
        voidTopBox = new javax.swing.JCheckBox();
        voidBottomBox = new javax.swing.JCheckBox();
        voidGlovesBox = new javax.swing.JCheckBox();
        voidRangeHelmBox = new javax.swing.JCheckBox();
        voidMeleeHelmBox = new javax.swing.JCheckBox();
        voidMageHelmBox = new javax.swing.JCheckBox();
        voidMaceBox = new javax.swing.JCheckBox();
        voidSealBox = new javax.swing.JCheckBox();
        xpPointsComboBox = new javax.swing.JComboBox();
        currentWorldLabel = new javax.swing.JLabel();
        worldTextField = new javax.swing.JTextField();
        pointsSeparator = new javax.swing.JSeparator();
        Separator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        buyXPLabel = new javax.swing.JLabel();

        setTitle("Texan's Pest Control Gui");
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));
        
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        buttonGroup1.add(meleeCombatButton);
        meleeCombatButton.setText("Melee");

        buttonGroup1.add(mageCombatButton);
        mageCombatButton.setText("Mage");

        buttonGroup1.add(rangeCombatButton);
        rangeCombatButton.setText("Range");

        buttonGroup2.add(specialAttackYesButton);
        specialAttackYesButton.setText("Yes");

        buttonGroup2.add(specialAttackNoButton);
        specialAttackNoButton.setText("No");

        specialAttackLabel.setText("Special Attack?");

        buttonGroup3.add(attackPortalButton);
        attackPortalButton.setText("Attack Portal");

        buttonGroup3.add(defendButton);
        defendButton.setText("Defend Knight");

        buttonGroup3.add(randomButton);
        randomButton.setText("Random");

        methodOfCombatLabel.setText("Method of Combat:");

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	if(meleeCombatButton.isSelected()) { TexanPestControl.setAttackStyle(1);}
            	if(mageCombatButton.isSelected()) { TexanPestControl.setAttackStyle(2);}
            	if(rangeCombatButton.isSelected()) { TexanPestControl.setAttackStyle(3);}
            	if(specialAttackYesButton.isSelected()) { TexanPestControl.setSpecialAttack(true);}
            	if(specialAttackNoButton.isSelected()) { TexanPestControl.setSpecialAttack(false);}
            	if(attackPortalButton.isSelected()) { TexanPestControl.setPlayStyle("attack");}
            	if(defendButton.isSelected()) { TexanPestControl.setPlayStyle("defend");}
            	if(randomButton.isSelected()) { TexanPestControl.setPlayStyle("random");}
            	if(voidBottomBox.isSelected()) { TexanPestControl.addToBuyItem("bottom"); }
            	if(voidGlovesBox.isSelected()) { TexanPestControl.addToBuyItem("gloves"); }
            	if(voidMageHelmBox.isSelected()) { TexanPestControl.addToBuyItem("mageHelm"); }
            	if(voidMeleeHelmBox.isSelected()) { TexanPestControl.addToBuyItem("meleeHelm"); }
            	if(voidRangeHelmBox.isSelected()) { TexanPestControl.addToBuyItem("rangerHelm"); }
            	if(voidTopBox.isSelected()) { TexanPestControl.addToBuyItem("top"); }
            	if(voidMaceBox.isSelected()) { TexanPestControl.addToBuyItem("mace"); }
            	if(voidSealBox.isSelected()) { TexanPestControl.addToBuyItem("seal"); }
            	TexanPestControl.setClanChat(ccTextField.getText().toString());
            	TexanPestControl.setCurrentWorld(worldTextField.getText().toString());
            	System.out.println(worldTextField.getText());
            	TexanPestControl.setXP(xpPointsComboBox.getSelectedItem().toString());
            	dispose();
            	TexanPestControl.setButtonClicked();
            }
        });

        clanChatLabel.setText("Clan Chat:");

        voidTopBox.setText("Void Top");

        voidBottomBox.setText("Void Bottoms");

        voidGlovesBox.setText("Void Gloves");

        voidRangeHelmBox.setText("Void Range Helm");

        voidMeleeHelmBox.setText("Void Melee Helm");

        voidMageHelmBox.setText("Void Mage Helm");

        voidMaceBox.setText("Void Mace");

        voidSealBox.setText("Void Seal");

        xpPointsComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "Attack", "Defence", "Strength", "HP", "Range", "Magic", "Prayer" }));

        currentWorldLabel.setText("Current World:");

        jLabel5.setText("Spending Points");

        buyXPLabel.setText("Buy XP:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Separator1)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(clanChatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ccTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(methodOfCombatLabel)
                                    .addComponent(specialAttackLabel))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(specialAttackYesButton)
                                    .addComponent(meleeCombatButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(specialAttackNoButton)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(mageCombatButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rangeCombatButton))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(randomButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(attackPortalButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(defendButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(currentWorldLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(worldTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(voidTopBox)
                                    .addGap(18, 18, 18)
                                    .addComponent(voidBottomBox)
                                    .addGap(18, 18, 18)
                                    .addComponent(voidGlovesBox)
                                    .addGap(18, 18, 18)
                                    .addComponent(voidRangeHelmBox))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(voidMeleeHelmBox)
                                    .addGap(18, 18, 18)
                                    .addComponent(voidMageHelmBox)
                                    .addGap(18, 18, 18)
                                    .addComponent(voidMaceBox)
                                    .addGap(18, 18, 18)
                                    .addComponent(voidSealBox))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(19, 19, 19)
                                    .addComponent(buyXPLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addComponent(xpPointsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pointsSeparator)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(attackPortalButton)
                    .addComponent(defendButton)
                    .addComponent(randomButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(meleeCombatButton)
                            .addComponent(mageCombatButton)
                            .addComponent(rangeCombatButton)
                            .addComponent(methodOfCombatLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(specialAttackNoButton)
                            .addComponent(specialAttackYesButton)
                            .addComponent(specialAttackLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clanChatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ccTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(currentWorldLabel)
                            .addComponent(worldTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(pointsSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voidTopBox)
                    .addComponent(voidBottomBox)
                    .addComponent(voidGlovesBox)
                    .addComponent(voidRangeHelmBox))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voidMeleeHelmBox)
                    .addComponent(voidMageHelmBox)
                    .addComponent(voidMaceBox)
                    .addComponent(voidSealBox))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buyXPLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xpPointsComboBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startButton)
                .addGap(23, 23, 23))
        );
        setVisible(true);
        pack();
    }// </editor-fold>//GEN-END:initComponents                                                   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OriginalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OriginalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OriginalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OriginalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OriginalGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JSeparator Separator1;
    private javax.swing.JRadioButton attackPortalButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    @SuppressWarnings("unused")
	private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JLabel buyXPLabel;
    private javax.swing.JTextField ccTextField;
    private javax.swing.JLabel clanChatLabel;
    private javax.swing.JLabel currentWorldLabel;
    private javax.swing.JRadioButton defendButton;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton mageCombatButton;
    private javax.swing.JRadioButton meleeCombatButton;
    private javax.swing.JLabel methodOfCombatLabel;
    private javax.swing.JSeparator pointsSeparator;
    private javax.swing.JRadioButton randomButton;
    private javax.swing.JRadioButton rangeCombatButton;
    private javax.swing.JLabel specialAttackLabel;
    private javax.swing.JRadioButton specialAttackNoButton;
    private javax.swing.JRadioButton specialAttackYesButton;
    private javax.swing.JButton startButton;
    private javax.swing.JCheckBox voidBottomBox;
    private javax.swing.JCheckBox voidGlovesBox;
    private javax.swing.JCheckBox voidMaceBox;
    private javax.swing.JCheckBox voidMageHelmBox;
    private javax.swing.JCheckBox voidMeleeHelmBox;
    private javax.swing.JCheckBox voidRangeHelmBox;
    private javax.swing.JCheckBox voidSealBox;
    private javax.swing.JCheckBox voidTopBox;
    private javax.swing.JTextField worldTextField;
    private javax.swing.JComboBox xpPointsComboBox;
    // End of variables declaration//GEN-END:variables
    // End of variables declaration                   
}
